### ISSUE TITLE
No pools displayed if a pool with mirror or multiple mirror vdevs in one pool exist

### ISSUE THREAD

**Issue by hyperbart** [FireDrunk/ZFSmond#4]
Pool with mirror or multiple mirrors results in a crash

No pools displayed at all anymore...

**Comment by hyperbart** [comment]
Same applies to "frankenstein" pools: pool with raidz and raidz2.

Haven't tested with a pool with two raidz's for example, but I think issue occurs there too..

**Comment by FireDrunk** [comment]
Define Frankenstein pools?
And please post a stacktrace of the error that occurs in the console.

**Comment by hyperbart** [comment]
Frankenstein pools = pools with a mix of different parity level vdevs, like a raidz and a raidz2 combined in one pool.

**Comment by hyperbart** [comment]
About the stacktrace:

192.168.4.60 - - [15/May/2015 16:23:01] "GET /api/pools HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/**init**.py", line 265, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/**init**.py", line 262, in error_router
    return self.handle_error(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/**init**.py", line 265, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/**init**.py", line 262, in error_router
    return self.handle_error(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/**init**.py", line 446, in wrapper
    resp = resource(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/**init**.py", line 550, in dispatch_request
    resp = meth(_args, *_kwargs)
  File "/root/zfsmond/models/zfs.py", line 20, in get
    pool_info['config'] = self.generate_config(raw_pool)
  File "/root/zfsmond/models/zfs.py", line 49, in generate_config
    'scan_stats': child['scan_stats']
KeyError: 'scan_stats'

**Comment by FireDrunk** [comment]
Fixed in commit:
https://github.com/FireDrunk/ZFSmond/commit/07a9f0c0ca9bd0378c42922e3f797c3bf9fdc5d9
